server:
  port: 50004

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
spring:
  zipkin:
    baseUrl: http://127.0.0.1:60000
    enabled: true
  sleuth:
    feign:
      enabled: true
      processor:
        enabled: true
    sampler:
      percentage: 100

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

management:
  security:
    enabled: false
